// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using webdemo.DBcontext;

namespace webdemo.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.32")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("webdemo.Models.Hanghoa", b =>
                {
                    b.Property<string>("MaHangHoa")
                        .HasColumnType("nvarchar(450)");

                    b.Property<double>("DonGia")
                        .HasColumnType("float");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.Property<string>("TenHangHoa")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaHangHoa");

                    b.ToTable("Hanghoas");

                    b.HasData(
                        new
                        {
                            MaHangHoa = "HH001",
                            DonGia = 32000.0,
                            SoLuong = 100,
                            TenHangHoa = "Sữa tươi Vinamilk"
                        },
                        new
                        {
                            MaHangHoa = "HH002",
                            DonGia = 55000.0,
                            SoLuong = 50,
                            TenHangHoa = "Bánh Chocopie"
                        },
                        new
                        {
                            MaHangHoa = "HH003",
                            DonGia = 4500.0,
                            SoLuong = 500,
                            TenHangHoa = "Mì Tôm Hảo Hảo"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
