<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\QuanLySinhVien.entities\QuanLySinhVien.entities.csproj" />
    <ProjectReference Include="..\QuanLySinhVienn.DAL\QuanLySinhVienn.DAL.csproj" />
  </ItemGroup>

</Project>
